### ISSUE TITLE
Private GitHub Repo URL does not work if prefixed with www

### ISSUE THREAD

**Issue by lucas-amberg** [3eif/gitmotion#6]
Unsure if this is intentional or not, but submitting GitHub repos that are private with a URL prefixed with `www.` are not accepted.

![image](https://github.com/user-attachments/assets/bfecadfe-9142-468a-bb62-a52269d5bc91)

Uploading the same URL without `www.` at the beginning works as intended.

**Comment by 3eif** [comment]
Thanks for catching this! Should be fixed in https://github.com/3eif/gitmotion/commit/3b42e34cd15044bf2c20c6dd6843f7c3fbed252d. It's not yet live, will push to prod once traffic dies down a bit.

**Comment by 3eif** [comment]
Should be live now! Thanks for reporting this.
